ENV["SINATRA_ENV"] ||= "development"

require_relative './config/environment'
require 'sinatra/activerecord/rake'
ActiveRecord::Base.logger = Logger.new(STDOUT) # this line prints out the SQL queries that are run in your console

task :console do
  Pry.start
end
